const data = {
	products: [
		{
			_id: "1",
			name: "Dried Beef Liver",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
        {
			_id: "2",
			name: "Sweet Potato Fries",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
        {
			_id: "3",
			name: "Peanut Butter Biscuits",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
        {
			_id: "4",
			name: "Raw Hide",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
        {
			_id: "5",
			name: "Dried Beef Liver",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
        {
			_id: "6",
			name: "Dried Beef Liver",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
	],
};
